# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: shugo256
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Tokyo
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 8
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
#           plugin_code: yes
#           plugin_code_days: 7
#           plugin_code_languages: rust, go, c++
#           plugin_code_lines: 12
#           plugin_code_load: 400
#           plugin_code_visibility: public
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_languages: yes
          plugin_languages_analysis_timeout: 20
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: repositories
          plugin_lines_skipped: m1-rinko, mss-2021-11, route-bucket-backend-placeholder, LabPDFs, OnseiTaiwaKihonKadai, onsei_taiwa_lib, MyFirstEverRailsProject, I_jikken, 3S
